name = "backend-ws"
main = "src/index.ts"
compatibility_date = "2025-10-28"
workers_dev = true

[[durable_objects.bindings]]
name = "ROOM"
class_name = "Room"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room"]